apiVersion: v1
kind: Service

metadata:
  name: mojito-service
  namespace: mojito

spec:
  selector:
    app: mojito

  ports:
    - protocol: TCP
      port: 3000
      targetPort: 80

  type: ClusterIP
